# docker-compose.yml
version: '3.8'
services:
  postgres:
      container_name: dev_crudify_postgres
      image: postgres:14.5
      restart: always
      env_file:
        - ./.env
      environment:
        POSTGRES_USER: myuser
        POSTGRES_PASSWORD: mypassword
        PGDATA: /var/lib/postgresql/data
        TZ: "GMT+4"
        PGTZ: "GMT+4"
      volumes:
        - postgres:/var/lib/postgresql/data
      ports:
        - '5432:5432'

volumes:
  postgres: